[versions]
agp = "8.5.2"
kotlin = "1.9.24"
compose-bom = "2024.05.00"
composeCompiler = "1.5.15"
coroutines = "1.8.1"
androidx-core = "1.13.1"
androidx-appcompat = "1.7.0"
material = "1.12.0"
activity-compose = "1.9.2"
navigation = "2.7.7"
hilt = "2.51.1"
hilt-ext = "1.2.0"
room = "2.6.1"
datastore = "1.1.1"
accompanist = "0.34.0"
play-services-location = "21.3.0"
work = "2.9.1"
timber = "5.0.1"
mockk = "1.13.10"
junit = "4.13.2"
androidx-test-ext = "1.1.5"
espresso = "3.5.1"
compose-test = "1.6.8"
ktlint = "12.1.1"
detekt = "1.23.6"
okhttp = "4.12.0"
okio = "3.9.0"
moshi = "1.15.1"
serialization = "1.6.3"
secrets = "2.0.1"
work-multiprocess = "2.9.1"
datetime = "0.6.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-ext" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "work-multiprocess" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-ext" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt-gradle = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
